-- WaliNet Manager: modul data usaha
-- Jalankan setelah supabase_setup.sql di Supabase SQL Editor.

-- ============================================================
-- 1. PAKET INTERNET
-- ============================================================
CREATE TABLE IF NOT EXISTS public.paket (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nama text NOT NULL,
  kecepatan text,
  harga numeric(14,2) NOT NULL DEFAULT 0,
  aktif boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- 2. PELANGGAN
-- ============================================================
CREATE TABLE IF NOT EXISTS public.pelanggan (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nama text NOT NULL,
  nomor_hp text,
  alamat text,
  mikrotik_user text,
  tipe text NOT NULL DEFAULT 'pppoe' CHECK (tipe IN ('pppoe','hotspot','lainnya')),
  paket_id bigint REFERENCES public.paket(id) ON DELETE SET NULL,
  tanggal_daftar date NOT NULL DEFAULT CURRENT_DATE,
  tanggal_jatuh_tempo date,
  status text NOT NULL DEFAULT 'aktif' CHECK (status IN ('aktif','terisolir','nonaktif')),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- 3. PEMBAYARAN
-- ============================================================
CREATE TABLE IF NOT EXISTS public.pembayaran (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  pelanggan_id bigint REFERENCES public.pelanggan(id) ON DELETE SET NULL,
  tanggal date NOT NULL DEFAULT CURRENT_DATE,
  jumlah numeric(14,2) NOT NULL DEFAULT 0,
  metode text NOT NULL DEFAULT 'tunai',
  keterangan text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- 4. VOUCHER
-- ============================================================
CREATE TABLE IF NOT EXISTS public.voucher (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  kode text NOT NULL,
  profile text,
  harga numeric(14,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'tersedia' CHECK (status IN ('tersedia','terpakai','kadaluarsa','nonaktif')),
  tanggal_dibuat timestamptz NOT NULL DEFAULT now(),
  tanggal_expired timestamptz,
  UNIQUE(owner_id, kode)
);

-- ============================================================
-- 5. KONEKSI MIKROTIK
-- Password/token jangan disimpan di frontend. Kolom rahasia ini
-- hanya placeholder server-side untuk tahap integrasi berikutnya.
-- ============================================================
CREATE TABLE IF NOT EXISTS public.mikrotik_connection (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nama text NOT NULL DEFAULT 'MikroTik Utama',
  host text,
  port integer NOT NULL DEFAULT 443,
  protocol text NOT NULL DEFAULT 'https' CHECK (protocol IN ('http','https')),
  aktif boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(owner_id)
);

-- ============================================================
-- 6. RLS: setiap tenant hanya melihat datanya sendiri.
-- Admin platform dapat membaca semua data.
-- ============================================================
ALTER TABLE public.paket ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pelanggan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pembayaran ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.voucher ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mikrotik_connection ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "paket_own" ON public.paket;
CREATE POLICY "paket_own" ON public.paket FOR ALL TO authenticated
USING (owner_id = auth.uid() OR public.is_walinet_admin())
WITH CHECK (owner_id = auth.uid() OR public.is_walinet_admin());

DROP POLICY IF EXISTS "pelanggan_own" ON public.pelanggan;
CREATE POLICY "pelanggan_own" ON public.pelanggan FOR ALL TO authenticated
USING (owner_id = auth.uid() OR public.is_walinet_admin())
WITH CHECK (owner_id = auth.uid() OR public.is_walinet_admin());

DROP POLICY IF EXISTS "pembayaran_own" ON public.pembayaran;
CREATE POLICY "pembayaran_own" ON public.pembayaran FOR ALL TO authenticated
USING (owner_id = auth.uid() OR public.is_walinet_admin())
WITH CHECK (owner_id = auth.uid() OR public.is_walinet_admin());

DROP POLICY IF EXISTS "voucher_own" ON public.voucher;
CREATE POLICY "voucher_own" ON public.voucher FOR ALL TO authenticated
USING (owner_id = auth.uid() OR public.is_walinet_admin())
WITH CHECK (owner_id = auth.uid() OR public.is_walinet_admin());

DROP POLICY IF EXISTS "mikrotik_own" ON public.mikrotik_connection;
CREATE POLICY "mikrotik_own" ON public.mikrotik_connection FOR ALL TO authenticated
USING (owner_id = auth.uid() OR public.is_walinet_admin())
WITH CHECK (owner_id = auth.uid() OR public.is_walinet_admin());

-- Index untuk dashboard dan pencarian.
CREATE INDEX IF NOT EXISTS pelanggan_owner_idx ON public.pelanggan(owner_id);
CREATE INDEX IF NOT EXISTS pelanggan_status_idx ON public.pelanggan(owner_id, status);
CREATE INDEX IF NOT EXISTS pembayaran_owner_date_idx ON public.pembayaran(owner_id, tanggal DESC);
CREATE INDEX IF NOT EXISTS voucher_owner_status_idx ON public.voucher(owner_id, status);
